/*
SQLyog Ultimate v10.42 
MySQL - 5.5.34 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('1',NULL,'inventario','Inventario');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('2','1','productos','Productos');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('3','1','gruposproductos','Grupos');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('4','1','marcas','Marcas');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('5','1','lineas','Lineas');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('6','1','familias','Familias');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('7','1','listaprecios','Lista de precios');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('8','1','ajusteinventario','Ajuste de inventario');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('9','1','movimientoinventario','Movimiento Inventario');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('10','1','exitenciaminima','Productos con existencia minima');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('11','1','existenciabaja','Reportes de existencias bajas');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('12','1','existenciasalta','Reportes de existencias altas');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('13',NULL,'ventas','Ventas');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('14','13','generarventa','Generar ventas');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('15','13','historialventas','Historial de ventas');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('16','13','anularventa','Anular ventas');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('17','13','devolucionventa','Devolucion de ventas');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('18','13','ventasporcliente','Ventas por cliente');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('19','13','gastospadre','Gastos');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('20','19','gastos','Gastos');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('21','19','tiposgasto','Tipos de gasto');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('22',NULL,'clientespadre','Clientes');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('23','22','clientes','Clientes');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('24','22','gruposcliente','Grupos');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('25','38','metodospago','Metodos de pago');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('27',NULL,'ingresos','Ingresos');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('28','27','registraringreo','Registrar ingreso');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('29','27','consultaringresos','Consulta de ingresos');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('30',NULL,'proveedores','Proveedores');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('31','30','proveedor','Proveedor');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('32',NULL,'reportes','Reportes');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('33','32','reporteutilidades','Reporte de utilidades');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('34','32','estadisticautilidades','Estadistica utilidades');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('35','32','utilidadesproductos','Utilidades por producto');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('36','32','utilidadescliente','Utilidades por cliente');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('37','32','utilidadesproveedor','Utiildades por proveedor');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('38',NULL,'opciones','Opciones');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('39','38','opcionesgenerales','Opciones');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('40','79','impuestos','Impuestos');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('41','79','condicionespago','Condiciones de pago');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('45','79','locales','Locales');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('46','79','region','Region');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('47','46','pais','Paises');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('48','46','estado','Estados');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('49','46','ciudad','Ciudades');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('50','38','usuariospadre','Usuarios');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('51','50','usuarios','Usuario');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('52','50','gruposusuarios','Grupos');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('53','79','precios','Precios');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('54','38','unidadesmedida','Unidades de medida');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('55','27','devolucioningreso','Devoluci&oacute;n de ingresos');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('56','1','stock','Stock Producto');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('57','46','zona','Zona de Distribución');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('58','27','ingresoexistencia','Registro de existencia');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('59',NULL,'transporte','Transporte');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('60','59','camiones','Camiones');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('62','13','promociones','Promociones');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('63','62','bonificaciones','Bonificaciones');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('64','62','descuentos','Descuentos');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('65','1','subfamilias','Sub Familias');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('66','1','subgruposproductos','Sub Grupos');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('67','32','costosdecompra','Costos de compra');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('70','73','historialpedidos','Bandeja de pedidos');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('71','59','consolidado','Consolidado de Carga');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('72','38','bancos','Bancos');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('73',NULL,'pedidos','Pedidos');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('74','1','categorias','Categorias');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('75','73','generarpedidos','Generar Pedidos');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('76','73','liquidacioncdc','Liquidacion CGC');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('77','38','cajas','Cajas');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('78','59','puntosReparticion','Puntos de Reparticion');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('79',NULL,'configuraciones','Configuraciones');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('80','73','clienterporatender','Clientes por atender');
insert into `opcion` (`nOpcion`, `nOpcionClase`, `cOpcionDescripcion`, `cOpcionNombre`) values('81','32','productoszona','Rotacion Productos');
